### ISSUE TITLE
learnvimscriptthehardway网站好像到期了

### ISSUE THREAD

**Issue by huhuang03** [spacewander/blogWithMarkdown#37]
http://learnvimscriptthehardway.onefloweroneworld.com/
好像已经到期了。网上好像也没有其他的地方能找到阅读。我想把文章内容移到gitbook。您看时候可行？

**Comment by spacewander** [comment]
我没问题。不过这件事您还得问问 @isayme 的意见。

**Comment by isayme** [comment]
啊, 好吧, 我看看还能不能续费...

**Comment by isayme** [comment]
@huhuang03 应该可以访问了
